definitions:
  document.Candidate:
    properties:
      address:
        type: string
      delegators:
        items:
          $ref: '#/definitions/document.Delegator'
        type: array
      description:
        $ref: '#/definitions/document.Description'
        type: object
      pub_key:
        type: string
      shares:
        type: integer
      update_time:
        type: string
      voting_power:
        type: number
    type: object
  document.Delegator:
    properties:
      address:
        type: string
      pub_key:
        type: string
      shares:
        type: integer
      update_time:
        type: string
    type: object
  document.DelegatorShares:
    properties:
      total_shares:
        type: integer
    type: object
  document.Description:
    properties:
      details:
        type: string
      identity:
        type: string
      moniker:
        type: string
      website:
        type: string
    type: object
host: 47.104.155.125:9080
info:
  contact: {}
  description: IRIS API Server that supports various light clients
  license:
    name: API Spec Document
    url: https://github.com/kaifei-bianjie/share/blob/master/api_spec.md
  title: IRIS SERVER API
  version: 0.1.0
paths:
  /candidates:
    get:
      consumes:
      - application/json
      description: the list of candidates
      parameters:
      - description: user address
        in: query
        name: address
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: per_page
        in: query
        name: per_page
        required: true
        type: integer
      - description: order
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: content of data
          schema:
            items:
              $ref: '#/definitions/document.Candidate'
            type: array
      summary: candidate list
      tags:
      - stake
  /delegators/{address}/candidates:
    get:
      consumes:
      - application/json
      description: list of candidate which delegated by address
      parameters:
      - description: user address
        in: path
        name: address
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: per_page
        in: query
        name: per_page
        required: true
        type: integer
      - description: order
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: content of data
          schema:
            items:
              $ref: '#/definitions/document.Candidate'
            type: array
      summary: delegator candidate list
      tags:
      - stake
  /delegators/{address}/candidates/{pub_key}:
    get:
      consumes:
      - application/json
      description: detail of candidate which delegated by address
      parameters:
      - description: user address
        in: path
        name: address
        required: true
        type: string
      - description: public key of candidate
        in: path
        name: pub_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: content of data
          schema:
            $ref: '#/definitions/document.Candidate'
            type: object
      summary: delegator candidate detail
      tags:
      - stake
  /shares/delegator/{address}:
    get:
      consumes:
      - application/json
      description: get total shares which own by a delegator
      parameters:
      - description: user address
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: content of data
          schema:
            $ref: '#/definitions/document.DelegatorShares'
            type: object
      summary: shares own by a delegator
      tags:
      - stake
  /txs:
    get:
      consumes:
      - application/json
      description: get list of tx
      parameters:
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: per_page
        in: query
        name: per_page
        required: true
        type: integer
      - description: wallet address
        in: query
        name: address
        required: true
        type: string
      - description: tx type
        enum:
        - send
        - receive
        - delegate
        - unbond
        in: query
        name: tx_type
        type: string
      - description: tx time
        in: query
        name: start_time
        type: string
      - description: tx time
        in: query
        name: end_time
        type: string
      - description: order
        enum:
        - -time
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: generate response data error, please see result
          schema:
            type: string
      summary: tx list
      tags:
      - txs
swagger: "2.0"
